### ISSUE TITLE
[Feature request] Optional template support and convenience function

### ISSUE THREAD

**Issue by nickjj** [mattupstate/flask-mail#108]
I'm new to flask and one of the first things I noticed was that the de-facto standard mail extension doesn't support templates out of the box. This seems reasonable given how low level it is, but what if it did just a tiny bit more?

#### Convenience function to send e-mail

It would match the call signature of Message() with a few more arguments and send the actual mail as the last step.

```
def send_mail(subject='',
              recipients=None,
              body=None,
              html=None,
              sender=None,
              cc=None,
              bcc=None,
              attachments=None,
              reply_to=None,
              date=None,
              charset=None,
              extra_headers=None,
              mail_options=None,
              rcpt_options=None,
              template_path=None,
              **kwargs):
```

##### Example using it:

```
send_mail('Thanks for signing up!', ['foo@example.com'])
```
##### Example using it with a template:

```
send_mail('Thanks for signing up!', ['foo@example.com'],
          template_path='user/mail/signup', user=current_user)
```

Notice how there's no file extension on the signup template. What would happen is, it will look for a `login.txt` version of the file and set the `message.body` to be that if it exists. Likewise, it will set `message.html` if it finds `login.html` at that path.

#### Implementation

I have already implemented this, wondering if it's worth sending a PR to make it a part of the mail extension instead of branching off a new extension or forking this one.

**Comment by jonafato** [comment]
I like the idea of templates here. A couple of questions / comments:

- How does this convenience function differ from [`flask.Mail.send_message`](https://pythonhosted.org/Flask-Mail/#flask_mail.Mail.send_message)?
- The `template_path` should probably be handled by the [extension configuration](https://pythonhosted.org/Flask-Mail/#configuring-flask-mail).
- I'm not a fan of the file extension being omitted. This is opinionated and restrictive regarding filenames, and all it saves if a few keystrokes per call. A case where this would become problematic: some developers name their templates with `.j2` or `.jinja.html` extensions.

**Comment by nickjj** [comment]
@jonafato It doesn't differ from `send_message`, I didn't even know that function existed. I implemented one locally just so I could feed it my extra template params.

The issue with using extension configuration is that the paths are tricky to determine for all use cases. For example my app has 3 blueprints. Each blueprint has its own dedicated template directory.

I would ideally want to have mail templates for those blueprints, each mail template would be isolated to the blueprint itself (optionally overridden at the project's template directory).

The way I have it setup now, the `user/mail/signup` path works without knowing anything about base template locations. The issue is I'm using a try/catch (catching IOError) if the path doesn't exist which is kind of hacky.

I basically just add `.txt` to the end of the template name, or `.html`. I see that it's a bit leaky to do this if you include maybe having .j2, .jinja or .jinja2 extensions. I wasn't sure how to solve that issue without having to define multiple template paths to the function call.

For example, compare:

```
send_mail('Thanks for signing up!', ['foo@example.com'],
          template_path='user/mail/signup', user=current_user)
```

Vs.

```
send_mail('Thanks for signing up!', ['foo@example.com'],
          [template_path='user/mail/signup.txt', template_path='user/mail/signup.html'], user=current_user)
```

The top one to me is much nicer looking. Perhaps there could be an extension configuration option which accepts a list of file extensions as a happy medium? Then we get the nice function call and limitless extension support. It could maybe default to `['txt', 'html', 'j2', 'jinja', 'jinja2']`?

**Comment by mattupstate** [comment]
As the idea stands I'm not sure how much value this would offer to users of Flask-Mail. It's very easy to write a function of your own to provide this feature.

**Comment by nickjj** [comment]
How would you write this easy function?

I had to duplicate the entire call signature of Message(), also I don't think I could use the existing `send_message` because I have to manually adjust the body/html properties before it gets sent.

**Comment by davidism** [comment]
~~~python
def send_rendered_message(*args, template=None, context=None, **kwargs):
    body = render_template(template, **context)
    return send_message(*args, body=body, **kwargs)
~~~

**Comment by nickjj** [comment]
@davidism,

How does **context work? It looks like it's defined as None but then you use **context when you call render template.

Ideally we should be able to send in multiple contexts so it supports the same call signature as `render_template`.

**Comment by mattupstate** [comment]
It all depends on your mail sending rules. It might look something like this:

```python
from flask import render_template

from my.app.module import mail

def send_mail(template=None, context=None, *args, **kwargs):
    if template is not None:
        if 'body' in kwargs:
            raise Exception('template and body arguments are mutually exclusive')
        elif 'html' in kwargs:
            raise Exception('template and html arguments are mutually exclusive')
        elif context is None:
            raise Excpetion('template and context arguments are mutually inclusive')
        kwargs['body'] = render_template(template + '.txt', **context)
        kwargs['html'] = render_template(template + '.html', **context)
    mail.send_message(*args, **kwargs)

# Example
context = {'hello': 'world'}
send_mail('Thanks for registering', ['joe@gmail.com'], template='path/to/registered_template', context=context)
```

**Comment by davidism** [comment]
I updated the code, although it was just a sample showing how straightforward it would be.  It's just a dictionary.  This is a pretty common pattern to use if two functions both allow keyword args, just pick which one you'd rather put in a dict.

I do something similar in my app, but the issue is that I don't want to use the Flask app's Jinja environment, I have a separate sandboxed env with separate settings, globals, etc. so that my users can write templates.  Including this function in Flask-Mail wouldn't help in this case.

**Comment by nickjj** [comment]
Interesting. I didn't know you could do that (I'm not too experienced with Python). But what you described is exactly what I was wishing for a few hours ago. "I wish there were a way to have 2 separate kwarg lists".

Thanks guys. Your implementations look a lot cleaner than what I had.
