### ISSUE TITLE
ImportError: No module named flask_mail - interpreter sees flask_mail, Flask does not.

### ISSUE THREAD

**Issue by kphretiq** [mattupstate/flask-mail#116]
I fear I am going mad:

I have installed in what I think is the "usual way" and have run on to the odd situation where flask_mail is seen just fine by the interpreter in my venv, but is not successfully imported into into flask. Sorry for the long paste, but I wanted you to be sure I wasn't enjoying a wholesome crack rock.

It appears that flask_mail is either not being successfully added as a flask extension or I can't read.

Thanks!

(venv)doug@kreplach:~/Projects/very-metal$ pip install flask-mail
Downloading/unpacking flask-mail
  Downloading Flask-Mail-0.9.1.tar.gz (45kB): 45kB downloaded
  Running setup.py (path:/tmp/pip-build-LKwVcb/flask-mail/setup.py) egg_info for package flask-mail
    
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Requirement already satisfied (use --upgrade to upgrade): Flask in ./venv/lib/python2.7/site-packages (from flask-mail)
Requirement already satisfied (use --upgrade to upgrade): blinker in ./venv/lib/python2.7/site-packages (from flask-mail)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in ./venv/lib/python2.7/site-packages (from Flask->flask-mail)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in ./venv/lib/python2.7/site-packages (from Flask->flask-mail)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in ./venv/lib/python2.7/site-packages (from Flask->flask-mail)
Installing collected packages: flask-mail
  Running setup.py install for flask-mail
    
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Successfully installed flask-mail
Cleaning up...
(venv)doug@kreplach:~/Projects/very-metal$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask_mail import Mail, Message
>>> 
(venv)doug@kreplach:~/Projects/very-metal$ head metal/hurlant.py
# -*- coding: utf-8 -*-
import datetime
import uuid
import random
import json
from io import BytesIO
import xml.etree.ElementTree as ET
from flask import Flask, render_template, make_response, request, url_for, g
from flask.ext import restful
from flask_mail import Mail, Message

(venv)doug@kreplach:~/Projects/very-metal$ foreman start
11:14:52 web.1  | started with pid 27390
11:14:52 web.1  | [2015-08-05 11:14:52 +0000] [27390] [INFO] Starting gunicorn 19.3.0
11:14:52 web.1  | [2015-08-05 11:14:52 +0000] [27390] [INFO] Listening at: http://0.0.0.0:5000 (27390)
11:14:52 web.1  | [2015-08-05 11:14:52 +0000] [27390] [INFO] Using worker: sync
11:14:52 web.1  | [2015-08-05 11:14:52 +0000] [27396] [INFO] Booting worker with pid: 27396
11:14:52 web.1  | [2015-08-05 11:14:52 +0000] [27396] [ERROR] Exception in worker process:
11:14:52 web.1  | Traceback (most recent call last):
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
11:14:52 web.1  |     worker.init_process()
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
11:14:52 web.1  |     self.wsgi = self.app.wsgi()
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
11:14:52 web.1  |     self.callable = self.load()
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
11:14:52 web.1  |     return self.load_wsgiapp()
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
11:14:52 web.1  |     return util.import_app(self.app_uri)
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
11:14:52 web.1  |     __import__(module)
11:14:52 web.1  |   File "/home/doug/Projects/very-metal/run.py", line 2, in <module>
11:14:52 web.1  |     from metal.hurlant import app
11:14:52 web.1  |   File "/home/doug/Projects/very-metal/metal/hurlant.py", line 10, in <module>
11:14:52 web.1  |     from flask_mail import Mail, Message
11:14:52 web.1  | ImportError: No module named flask_mail
11:14:52 web.1  | Traceback (most recent call last):
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
11:14:52 web.1  |     worker.init_process()
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
11:14:52 web.1  |     self.wsgi = self.app.wsgi()
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
11:14:52 web.1  |     self.callable = self.load()
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
11:14:52 web.1  |     return self.load_wsgiapp()
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
11:14:52 web.1  |     return util.import_app(self.app_uri)
11:14:52 web.1  |   File "/home/doug/.local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
11:14:52 web.1  |     __import__(module)
11:14:52 web.1  |   File "/home/doug/Projects/very-metal/run.py", line 2, in <module>
11:14:52 web.1  |     from metal.hurlant import app
11:14:52 web.1  |   File "/home/doug/Projects/very-metal/metal/hurlant.py", line 10, in <module>
11:14:52 web.1  |     from flask_mail import Mail, Message
11:14:52 web.1  | ImportError: No module named flask_mail
11:14:52 web.1  | [2015-08-05 11:14:52 +0000] [27396] [INFO] Worker exiting (pid: 27396)
11:14:52 web.1  | [2015-08-05 11:14:52 +0000] [27390] [INFO] Shutting down: Master
11:14:52 web.1  | [2015-08-05 11:14:52 +0000] [27390] [INFO] Reason: Worker failed to boot.
11:14:52 web.1  | exited with code 3
11:14:52 system | sending SIGTERM to all processes

(venv)doug@kreplach:~/Projects/very-metal$ pip freeze > requirements.txt 
(venv)doug@kreplach:~/Projects/very-metal$ cat requirements.txt 
Flask==0.10.1
Flask-Mail==0.9.1
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.10.4
argparse==1.2.1
blinker==1.4
itsdangerous==0.24
wsgiref==0.1.2

**Comment by davidism** [comment]
[Please format your code properly.](https://guides.github.com/features/mastering-markdown/)  Are you sure gunicorn is running your app in the same env?

**Comment by kphretiq** [comment]
Okey doke.

**Comment by thecodingconductor** [comment]
I'm having the same exact problem. It's driving me nuts...

**Comment by SeeH1OvO** [comment]
hey,bro! I also encountered the same problem! If you have checked the code and there are no issues, and if you are using pycharm, and you only perform library installation under Terminal in pycharm when creating a virtual environment, you may report an error as a result. My suggestion is that if you are a Windows system, please open the command line in Win+R and download the library: pip install Flask-Mail
