### ISSUE TITLE
Missing mail state after init_app()

### ISSUE THREAD

**Issue by paulgoetze** [mattupstate/flask-mail#175]
When using an App class with the application factory approach with flask v1.1.1, the mail.state after running `init_app()` has a None value: 

```python
from flask import Flask
from flask_mail import Mail

mail = Mail()

class App(Flask):
    def __init__(self):
        Flask.__init__(self, __name__)
        # load config etc.

        # does not write the state into global mail object:
        mail.init_app(self)

        # workaround:
        mail.state = mail.init_app(self)
```

This means, the [provided documentation](https://pythonhosted.org/Flask-Mail/#configuring-flask-mail) is not correct.

You would need the workaround of assigning the state in order to be able to import `mail` from this module and run `mail.send(message)` (else the connection host won’t be available).
Another approach is to get `mail` from the current app’s extensions (as e.g. [flask-security](https://github.com/mattupstate/flask-security/blob/develop/flask_security/utils.py#L403-L404) does it), like:

```python
mail = current_app.extensions.get('mail')
mail.send(message)
```

**Comment by paulgoetze** [comment]
Sorry, not an issue actually. I accidentally had the `TESTING` environment var set to True, so email sending was suppressed. The mail.state is still not set if you use init_app() after the Mail() initialization without an app, but this is not an issue for sending emails.

**Comment by Atreyagaurav** [comment]
This is a real issue in my opinion. Not setting the state in init_app() prevents sending mail if it was first initialized without an app, hence either the documentation needs to mention that or the code needs to be corrected.
