### ISSUE TITLE
Emails not suppressed when app.config['TESTING'] is True

### ISSUE THREAD

**Issue by raj-kesavan** [mattupstate/flask-mail#96]
I'm using nosetests with a setup_func that includes `app.config['TESTING'] = True` and a teardown_func that includes `app.config['TESTING'] = False`. Every test function is decorated with `with_setup(setup_func, teardown_func)`.
My mails are still being sent even though TESTING is true. If I manually put `if app.config['TESTING'] is False:` before my `mail.send`'s, my mails are not sent - which means that TESTING is indeed True during my tests.

Any ideas?

**Comment by xsteadfastx** [comment]
the same for me. it will always send mails. if i print app.config['TESTING'] right before my mail "sending mail" function it tells me that its "True". i dont know what else to do.

**Comment by jamesonjlee** [comment]
if you are attempting to change the send behavior after initializing the mail app, you will need to do `mail.suppress = True`

it might be worth adding that back into the mail.send function to also suppress on app.config['TESTING']

**Comment by xsteadfastx** [comment]
hey thanks for your help. it worked for me. it was some brain twisting but now it does what it should do :)
